


// Action type enum
export let UserActionType = /*#__PURE__*/function (UserActionType) {UserActionType["LOCKED_APP"] = "LOCKED_APP";UserActionType["AUTH_SUCCESS"] = "AUTH_SUCCESS";UserActionType["AUTH_ERROR"] = "AUTH_ERROR";UserActionType["INTERRUPT_BIOMETRICS"] = "INTERRUPT_BIOMETRICS";UserActionType["LOGIN"] = "LOGIN";UserActionType["LOGOUT"] = "LOGOUT";UserActionType["ON_PERSISTED_DATA_LOADED"] = "ON_PERSISTED_DATA_LOADED";UserActionType["PASSWORD_SET"] = "PASSWORD_SET";UserActionType["PASSWORD_UNSET"] = "PASSWORD_UNSET";UserActionType["SEEDPHRASE_BACKED_UP"] = "SEEDPHRASE_BACKED_UP";UserActionType["SEEDPHRASE_NOT_BACKED_UP"] = "SEEDPHRASE_NOT_BACKED_UP";UserActionType["BACK_UP_SEEDPHRASE_VISIBLE"] = "BACK_UP_SEEDPHRASE_VISIBLE";UserActionType["BACK_UP_SEEDPHRASE_NOT_VISIBLE"] = "BACK_UP_SEEDPHRASE_NOT_VISIBLE";UserActionType["PROTECT_MODAL_VISIBLE"] = "PROTECT_MODAL_VISIBLE";UserActionType["PROTECT_MODAL_NOT_VISIBLE"] = "PROTECT_MODAL_NOT_VISIBLE";UserActionType["LOADING_SET"] = "LOADING_SET";UserActionType["LOADING_UNSET"] = "LOADING_UNSET";UserActionType["SET_GAS_EDUCATION_CAROUSEL_SEEN"] = "SET_GAS_EDUCATION_CAROUSEL_SEEN";UserActionType["SET_APP_THEME"] = "SET_APP_THEME";UserActionType["CHECKED_AUTH"] = "CHECKED_AUTH";UserActionType["SET_APP_SERVICES_READY"] = "SET_APP_SERVICES_READY";return UserActionType;}({});























// User actions






























































/**
 * User actions union type
 */