import { isUUID } from './isUUID';

/**
 * A channel id is used as the permission origin of an SDK dapp connection, so it
 * shares its namespace with the hostnames used by dapps opened in the in-app browser.
 * Only the uuid format generated by the SDK is accepted, otherwise a deeplink could
 * claim an arbitrary origin (e.g. the hostname of a legitimate dapp) and have its
 * permissions displayed and stored under that identity.
 */
export const isValidChannelId = (channelId?: string): channelId is string =>
  typeof channelId === 'string' && isUUID(channelId);

/**
 * The originator identity is displayed to the user in the connection approval flow
 * and is fully controlled by the caller of the deeplink, so reject anything that
 * cannot be rendered as a dapp identity.
 */
export const hasValidOriginatorIdentity = (
  originatorInfo: unknown,
): originatorInfo is { url: string; title: string } => {
  if (typeof originatorInfo !== 'object' || originatorInfo === null) {
    return false;
  }

  const { url, title } = originatorInfo as { url?: unknown; title?: unknown };

  return typeof url === 'string' && typeof title === 'string';
};
