












export let TOKENS_WITH_DEFAULT_OPTIONS = /*#__PURE__*/function (TOKENS_WITH_DEFAULT_OPTIONS) {TOKENS_WITH_DEFAULT_OPTIONS["ETH"] = "ETH";TOKENS_WITH_DEFAULT_OPTIONS["STAKED_ETH"] = "STAKED_ETH";TOKENS_WITH_DEFAULT_OPTIONS["USDT"] = "USDT";TOKENS_WITH_DEFAULT_OPTIONS["USDC"] = "USDC";TOKENS_WITH_DEFAULT_OPTIONS["DAI"] = "DAI";TOKENS_WITH_DEFAULT_OPTIONS["LINK"] = "LINK";TOKENS_WITH_DEFAULT_OPTIONS["MATIC"] = "MATIC";return TOKENS_WITH_DEFAULT_OPTIONS;}({});