import { NETWORKS_CHAIN_ID } from './network';

export let FIAT_ORDER_PROVIDERS = /*#__PURE__*/function (FIAT_ORDER_PROVIDERS) {FIAT_ORDER_PROVIDERS["WYRE"] = "WYRE";FIAT_ORDER_PROVIDERS["WYRE_APPLE_PAY"] = "WYRE_APPLE_PAY";FIAT_ORDER_PROVIDERS["TRANSAK"] = "TRANSAK";FIAT_ORDER_PROVIDERS["MOONPAY"] = "MOONPAY";




  // The key for fiat on-ramp aggregator
  FIAT_ORDER_PROVIDERS["AGGREGATOR"] = "AGGREGATOR";return FIAT_ORDER_PROVIDERS;}({});


export let FIAT_ORDER_STATES = /*#__PURE__*/function (FIAT_ORDER_STATES) {FIAT_ORDER_STATES["PENDING"] = "PENDING";FIAT_ORDER_STATES["FAILED"] = "FAILED";FIAT_ORDER_STATES["COMPLETED"] = "COMPLETED";FIAT_ORDER_STATES["CANCELLED"] = "CANCELLED";FIAT_ORDER_STATES["CREATED"] = "CREATED";return FIAT_ORDER_STATES;}({});







export const FORMATTED_NETWORK_NAMES = {
  [NETWORKS_CHAIN_ID.MAINNET]: 'Ethereum Mainnet',
  [NETWORKS_CHAIN_ID.BSC]: 'Binance Smart Chain',
  [NETWORKS_CHAIN_ID.POLYGON]: 'Polygon',
  [NETWORKS_CHAIN_ID.AVAXCCHAIN]: 'Avalanche',
  [NETWORKS_CHAIN_ID.CELO]: 'Celo',
  [NETWORKS_CHAIN_ID.FANTOM]: 'Fantom'
};

export const NATIVE_ADDRESS = '0x0000000000000000000000000000000000000000';