var PAGINATION_OPERATIONS = /*#__PURE__*/function (PAGINATION_OPERATIONS) {PAGINATION_OPERATIONS[PAGINATION_OPERATIONS["GET_FIRST_PAGE"] = 0] = "GET_FIRST_PAGE";PAGINATION_OPERATIONS[PAGINATION_OPERATIONS["GET_NEXT_PAGE"] = 1] = "GET_NEXT_PAGE";PAGINATION_OPERATIONS[PAGINATION_OPERATIONS["GET_PREVIOUS_PAGE"] = -1] = "GET_PREVIOUS_PAGE";return PAGINATION_OPERATIONS;}(PAGINATION_OPERATIONS || {});





export default PAGINATION_OPERATIONS;