import {
  SRP_GUIDE_URL,
  NON_CUSTODIAL_WALLET_URL,
  KEEP_SRP_SAFE_URL,
  LEARN_MORE_URL,
  WHY_TRANSACTION_TAKE_TIME_URL,
  SIMULATION_DETALS_ARTICLE_URL,
  TOKEN_APPROVAL_SPENDING_CAP,
  CONNECTING_TO_A_DECEPTIVE_SITE,
  CONNECTING_TO_DEPRECATED_NETWORK,
  HOWTO_MANAGE_METAMETRICS,
  CONSENSYS_PRIVACY_POLICY,
  SES_URL,
  KEYSTONE_SUPPORT,
  KEYSTONE_LEARN_MORE,
  KEYSTONE_SUPPORT_VIDEO,
  NGRAVE_LEARN_MORE,
  NGRAVE_BUY,
  CHAINLIST_URL,
  MM_ETHERSCAN_URL,
  LINEA_GOERLI_BLOCK_EXPLORER,
  LINEA_SEPOLIA_BLOCK_EXPLORER,
  LINEA_MAINNET_BLOCK_EXPLORER,
  MAINNET_BLOCK_EXPLORER,
  SEPOLIA_BLOCK_EXPLORER,
  MAINNET_DEFAULT_RPC_URL,
  LINEA_DEFAULT_RPC_URL,
  MM_PHISH_DETECT_URL,
  MM_BLOCKLIST_ISSUE_URL,
  PHISHFORT_BLOCKLIST_ISSUE_URL,
  MM_APP_CONFIG_URL,
  MM_APP_CONFIG_TEST_URL,
  MM_DEPRECATED_NETWORKS,
  MM_APP_STORE_LINK,
  MM_PLAY_STORE_LINK,
  MM_SDK_DEEPLINK,
  FALSE_POSITIVE_REPORT_BASE_URL,
  UTM_SOURCE,
  SEPOLIA_FAUCET,
  LINEA_FAUCET,
  ADD_CUSTOM_NETWORK_ARTCILE,
  LEDGER_SUPPORT_LINK,
  GOERLI_DEPRECATED_ARTICLE,
  ETHEREUM_LOGO,
  HOW_TO_MANAGE_METRAMETRICS_SETTINGS,
  SOLANA_NEW_FEATURE_CONTENT_LEARN_MORE,
} from './urls';

describe('urls constants', () => {
  const allUrls = {
    SRP_GUIDE_URL,
    NON_CUSTODIAL_WALLET_URL,
    KEEP_SRP_SAFE_URL,
    LEARN_MORE_URL,
    WHY_TRANSACTION_TAKE_TIME_URL,
    SIMULATION_DETALS_ARTICLE_URL,
    TOKEN_APPROVAL_SPENDING_CAP,
    CONNECTING_TO_A_DECEPTIVE_SITE,
    CONNECTING_TO_DEPRECATED_NETWORK,
    HOWTO_MANAGE_METAMETRICS,
    CONSENSYS_PRIVACY_POLICY,
    SES_URL,
    KEYSTONE_SUPPORT,
    KEYSTONE_LEARN_MORE,
    KEYSTONE_SUPPORT_VIDEO,
    NGRAVE_LEARN_MORE,
    NGRAVE_BUY,
    CHAINLIST_URL,
    MM_ETHERSCAN_URL,
    LINEA_GOERLI_BLOCK_EXPLORER,
    LINEA_SEPOLIA_BLOCK_EXPLORER,
    LINEA_MAINNET_BLOCK_EXPLORER,
    MAINNET_BLOCK_EXPLORER,
    SEPOLIA_BLOCK_EXPLORER,
    MAINNET_DEFAULT_RPC_URL,
    LINEA_DEFAULT_RPC_URL,
    MM_PHISH_DETECT_URL,
    MM_BLOCKLIST_ISSUE_URL,
    PHISHFORT_BLOCKLIST_ISSUE_URL,
    MM_APP_CONFIG_URL,
    MM_APP_CONFIG_TEST_URL,
    MM_DEPRECATED_NETWORKS,
    MM_APP_STORE_LINK,
    MM_PLAY_STORE_LINK,
    MM_SDK_DEEPLINK,
    FALSE_POSITIVE_REPORT_BASE_URL,
    SEPOLIA_FAUCET,
    LINEA_FAUCET,
    ADD_CUSTOM_NETWORK_ARTCILE,
    LEDGER_SUPPORT_LINK,
    GOERLI_DEPRECATED_ARTICLE,
    ETHEREUM_LOGO,
    HOW_TO_MANAGE_METRAMETRICS_SETTINGS,
    SOLANA_NEW_FEATURE_CONTENT_LEARN_MORE,
  };

  it('all URL constants are non-empty strings', () => {
    Object.entries(allUrls).forEach(([name, url]) => {
      expect(typeof url).toBe('string');
      expect(url.length).toBeGreaterThan(0);
    });
  });

  it('all http/https URLs start with https://', () => {
    const httpUrls = Object.entries(allUrls).filter(
      ([name]) =>
        !['MM_APP_STORE_LINK', 'MM_PLAY_STORE_LINK', 'MM_SDK_DEEPLINK'].includes(name),
    );
    httpUrls.forEach(([name, url]) => {
      expect(url).toMatch(/^https?:\/\//);
    });
  });

  it('exports UTM_SOURCE as a string', () => {
    expect(UTM_SOURCE).toBe('metamask-ppom');
  });

  it('block explorer URLs point to known explorers', () => {
    expect(MAINNET_BLOCK_EXPLORER).toContain('etherscan.io');
    expect(SEPOLIA_BLOCK_EXPLORER).toContain('etherscan.io');
    expect(LINEA_MAINNET_BLOCK_EXPLORER).toContain('lineascan.build');
  });

  it('RPC URLs contain infura', () => {
    expect(MAINNET_DEFAULT_RPC_URL).toContain('infura.io');
    expect(LINEA_DEFAULT_RPC_URL).toContain('infura.io');
  });
});
