var AUTHENTICATION_TYPE = /*#__PURE__*/function (AUTHENTICATION_TYPE) {AUTHENTICATION_TYPE["BIOMETRIC"] = "biometrics";AUTHENTICATION_TYPE["PASSCODE"] = "device_passcode";AUTHENTICATION_TYPE["REMEMBER_ME"] = "remember_me";AUTHENTICATION_TYPE["PASSWORD"] = "password";AUTHENTICATION_TYPE["UNKNOWN"] = "unknown";return AUTHENTICATION_TYPE;}(AUTHENTICATION_TYPE || {});







export default AUTHENTICATION_TYPE;