



export let Display = /*#__PURE__*/function (Display) {Display["Block"] = "block";Display["Grid"] = "grid";Display["InlineBlock"] = "inline-block";Display["Inline"] = "inline";Display["InlineFlex"] = "inline-flex";Display["InlineGrid"] = "inline-grid";Display["ListItem"] = "list-item";Display["None"] = "none";return Display;}({});










export let BorderStyle = /*#__PURE__*/function (BorderStyle) {BorderStyle["dashed"] = "dashed";BorderStyle["solid"] = "solid";BorderStyle["dotted"] = "dotted";BorderStyle["double"] = "double";BorderStyle["none"] = "none";return BorderStyle;}({});







export let BorderColor = /*#__PURE__*/function (BorderColor) {BorderColor["borderDefault"] = "border-default";BorderColor["borderMuted"] = "border-muted";BorderColor["primaryDefault"] = "primary-default";BorderColor["primaryAlternative"] = "primary-alternative";BorderColor["primaryMuted"] = "primary-muted";BorderColor["errorDefault"] = "error-default";BorderColor["errorAlternative"] = "error-alternative";BorderColor["errorMuted"] = "error-muted";BorderColor["warningDefault"] = "warning-default";BorderColor["warningMuted"] = "warning-muted";BorderColor["successDefault"] = "success-default";BorderColor["successMuted"] = "success-muted";BorderColor["infoDefault"] = "info-default";BorderColor["infoMuted"] = "info-muted";BorderColor["mainnet"] = "mainnet";BorderColor["goerli"] = "goerli";BorderColor["sepolia"] = "sepolia";BorderColor["lineaGoerli"] = "linea-goerli";BorderColor["lineaSepolia"] = "linea-sepolia";BorderColor["lineaMainnet"] = "linea-mainnet";BorderColor["transparent"] = "transparent";BorderColor["localhost"] = "localhost";BorderColor["backgroundDefault"] = "background-default";






















  // exception for border color when element is meant to look "cut out"
  return BorderColor;}({});



































export let JustifyContent = /*#__PURE__*/function (JustifyContent) {JustifyContent["flexStart"] = "flex-start";JustifyContent["flexEnd"] = "flex-end";JustifyContent["center"] = "center";JustifyContent["spaceAround"] = "space-around";JustifyContent["spaceBetween"] = "space-between";JustifyContent["spaceEvenly"] = "space-evenly";return JustifyContent;}({});








export let FlexDirection = /*#__PURE__*/function (FlexDirection) {FlexDirection["Row"] = "row";FlexDirection["RowReverse"] = "row-reverse";FlexDirection["Column"] = "column";FlexDirection["ColumnReverse"] = "column-reverse";return FlexDirection;}({});






export let AlignItems = /*#__PURE__*/function (AlignItems) {AlignItems["flexStart"] = "flex-start";AlignItems["flexEnd"] = "flex-end";AlignItems["center"] = "center";AlignItems["baseline"] = "baseline";AlignItems["stretch"] = "stretch";return AlignItems;}({});







export let TextAlign = /*#__PURE__*/function (TextAlign) {TextAlign["left"] = "left";TextAlign["right"] = "right";TextAlign["center"] = "center";return TextAlign;}({});





export let BlockSize = /*#__PURE__*/function (BlockSize) {BlockSize["Zero"] = "0";BlockSize["Half"] = "1/2";BlockSize["OneThird"] = "1/3";BlockSize["TwoThirds"] = "2/3";BlockSize["OneFourth"] = "1/4";BlockSize["TwoFourths"] = "2/4";BlockSize["ThreeFourths"] = "3/4";BlockSize["OneFifth"] = "1/5";BlockSize["TwoFifths"] = "2/5";BlockSize["ThreeFifths"] = "3/5";BlockSize["FourFifths"] = "4/5";BlockSize["OneSixth"] = "1/6";BlockSize["TwoSixths"] = "2/6";BlockSize["ThreeSixths"] = "3/6";BlockSize["FourSixths"] = "4/6";BlockSize["FiveSixths"] = "5/6";BlockSize["OneTwelfth"] = "1/12";BlockSize["TwoTwelfths"] = "2/12";BlockSize["ThreeTwelfths"] = "3/12";BlockSize["FourTwelfths"] = "4/12";BlockSize["FiveTwelfths"] = "5/12";BlockSize["SixTwelfths"] = "6/12";BlockSize["SevenTwelfths"] = "7/12";BlockSize["EightTwelfths"] = "8/12";BlockSize["NineTwelfths"] = "9/12";BlockSize["TenTwelfths"] = "10/12";BlockSize["ElevenTwelfths"] = "11/12";BlockSize["Screen"] = "screen";BlockSize["Max"] = "max";BlockSize["Min"] = "min";BlockSize["Full"] = "full";return BlockSize;}({});

































export let Color = /*#__PURE__*/function (Color) {Color["backgroundDefault"] = "background-default";Color["backgroundAlternative"] = "background-alternative";Color["backgroundMuted"] = "background-muted";Color["textDefault"] = "text-default";Color["textAlternative"] = "text-alternative";Color["textMuted"] = "text-muted";Color["iconDefault"] = "icon-default";Color["iconAlternative"] = "icon-alternative";Color["iconMuted"] = "icon-muted";Color["borderDefault"] = "border-default";Color["borderMuted"] = "border-muted";Color["overlayDefault"] = "overlay-default";Color["overlayInverse"] = "overlay-inverse";Color["primaryDefault"] = "primary-default";Color["primaryAlternative"] = "primary-alternative";Color["primaryMuted"] = "primary-muted";Color["primaryInverse"] = "primary-inverse";Color["errorDefault"] = "error-default";Color["errorAlternative"] = "error-alternative";Color["errorMuted"] = "error-muted";Color["errorInverse"] = "error-inverse";Color["warningDefault"] = "warning-default";Color["warningMuted"] = "warning-muted";Color["warningInverse"] = "warning-inverse";Color["successDefault"] = "success-default";Color["successMuted"] = "success-muted";Color["successInverse"] = "success-inverse";Color["infoDefault"] = "info-default";Color["infoMuted"] = "info-muted";Color["infoInverse"] = "info-inverse";Color["mainnet"] = "mainnet";Color["goerli"] = "goerli";Color["sepolia"] = "sepolia";Color["lineaGoerli"] = "linea-goerli";Color["lineaGoerliInverse"] = "linea-goerli-inverse";Color["lineaSepolia"] = "linea-sepolia";Color["lineaSepoliaInverse"] = "linea-sepolia-inverse";Color["lineaMainnet"] = "linea-mainnet";Color["lineaMainnetInverse"] = "linea-mainnet-inverse";Color["transparent"] = "transparent";Color["localhost"] = "localhost";Color["inherit"] = "inherit";Color["goerliInverse"] = "goerli-inverse";Color["sepoliaInverse"] = "sepolia-inverse";return Color;}({});














































export let BackgroundColor = /*#__PURE__*/function (BackgroundColor) {BackgroundColor["backgroundDefault"] = "background-default";BackgroundColor["backgroundAlternative"] = "background-alternative";BackgroundColor["backgroundMuted"] = "background-muted";BackgroundColor["backgroundAlternativeSoft"] = "background-alternative-soft";BackgroundColor["backgroundHover"] = "background-hover";BackgroundColor["backgroundPressed"] = "background-pressed";BackgroundColor["iconDefault"] = "icon-default";BackgroundColor["iconAlternative"] = "icon-alternative";BackgroundColor["iconMuted"] = "icon-muted";BackgroundColor["overlayDefault"] = "overlay-default";BackgroundColor["overlayAlternative"] = "overlay-alternative";BackgroundColor["primaryDefault"] = "primary-default";BackgroundColor["primaryAlternative"] = "primary-alternative";BackgroundColor["primaryMuted"] = "primary-muted";BackgroundColor["errorDefault"] = "error-default";BackgroundColor["errorAlternative"] = "error-alternative";BackgroundColor["errorMuted"] = "error-muted";BackgroundColor["warningDefault"] = "warning-default";BackgroundColor["warningMuted"] = "warning-muted";BackgroundColor["successDefault"] = "success-default";BackgroundColor["successMuted"] = "success-muted";BackgroundColor["infoDefault"] = "info-default";BackgroundColor["infoMuted"] = "info-muted";BackgroundColor["mainnet"] = "mainnet";BackgroundColor["goerli"] = "goerli";BackgroundColor["sepolia"] = "sepolia";BackgroundColor["lineaGoerli"] = "linea-goerli";BackgroundColor["lineaSepolia"] = "linea-sepolia";BackgroundColor["lineaMainnet"] = "linea-mainnet";BackgroundColor["transparent"] = "transparent";BackgroundColor["localhost"] = "localhost";return BackgroundColor;}({});

































export let BorderRadius = /*#__PURE__*/function (BorderRadius) {
  /**
   * 2px
   */BorderRadius["XS"] = "xs";

  /**
   * 4px
   */BorderRadius["SM"] = "sm";

  /**
   * 6px
   */BorderRadius["MD"] = "md";

  /**
   * 8px
   */BorderRadius["LG"] = "lg";

  /**
   * 12px
   */BorderRadius["XL"] = "xl";

  /**
   * 0
   */BorderRadius["none"] = "none";

  /**
   * 9999px
   */BorderRadius["pill"] = "pill";

  /**
   * 50%
   */BorderRadius["full"] = "full";return BorderRadius;}({});



export let FlexWrap = /*#__PURE__*/function (FlexWrap) {FlexWrap["Wrap"] = "wrap";FlexWrap["WrapReverse"] = "wrap-reverse";FlexWrap["NoWrap"] = "nowrap";return FlexWrap;}({});




































































































































/**
 * Polymorphic props based on Ohans Emmanuel's article below
 * https://blog.logrocket.com/build-strongly-typed-polymorphic-components-react-typescript/#ensuring-as-prop-only-receives-valid-html-element-strings
 */

/**
 * Uses generic type C to create polymorphic ref type
 */



/**
 * Uses generic type C to define the type for the polymorphic "as" prop
 * "as" can be used to override the default HTML element
 */








/**
 * Omits the as prop and props from component definition
 */


/**
 * Accepts 2 generic types: C which represents the as prop and the component props - Props
 */













/**
 * Includes all style utility props. This should be used to extend the props of a component.
 */








































































































































































































/**
 * Box component props.
 */
// TODO: Convert to a `type` in a future major version.
// eslint-disable-next-line @typescript-eslint/consistent-type-definitions