#!/usr/bin/env python3
"""Generate the JS->TS migration inventory markdown from js-ts-inventory.json."""
import json
import os
import collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = json.load(open(os.path.join(ROOT, "scripts", "js-ts-inventory.json")))
ROWS = DATA["rows"]
OUT_DIR = os.path.join(ROOT, "docs", "js-ts-migration")
os.makedirs(OUT_DIR, exist_ok=True)

WS_TITLES = {
    "A_util": "Workstream A — Utilities (`app/util/**`)",
    "B_base": "Workstream B — Base components (`app/components/Base/**`)",
    "C_ui": "Workstream C — Shared UI components (`app/components/UI/**`)",
    "D_views": "Workstream D — Views/screens (`app/components/Views/**`)",
    "E_complib": "Workstream E — Component library (`app/component-library/**`)",
    "F_other": "Workstream F — Remaining app subtrees (`app/**`)",
}

# Finer sub-stream assignment for F_other and the large streams, to enable more
# parallel sessions with disjoint file sets.
def substream(r):
    f = r["file"]
    w = r["workstream"]
    if w == "A_util":
        return "A — util"
    if w == "B_base":
        return "B — Base"
    if w == "C_ui":
        if f.startswith("app/components/UI/Swaps/"):
            return "C1 — UI/Swaps"
        return "C2 — UI (non-Swaps)"
    if w == "D_views":
        if f.startswith("app/components/Views/confirmations/legacy/"):
            return "D2 — Views/confirmations/legacy"
        if f.startswith("app/components/Views/confirmations/"):
            return "D2 — Views/confirmations/legacy"
        if f.startswith("app/components/Views/Settings/"):
            return "D3 — Views/Settings"
        return "D1 — Views (standalone)"
    if w == "F_other":
        if f.startswith("app/actions/"):
            return "F1 — actions"
        if f.startswith("app/reducers/"):
            return "F2 — reducers"
        if f.startswith("app/store/"):
            return "F3 — store/migrations"
        if f.startswith("app/core/"):
            return "F4 — core services"
        if f.startswith("app/constants/") or f.startswith("app/components/Nav/") \
           or f.startswith("app/lib/") or f.startswith("app/__mocks__/") \
           or f.startswith("app/images/"):
            return "F5 — constants/nav/lib/mocks/images"
        return "F6 — misc"
    return WS_TITLES.get(w, w)


def order_key(r):
    # leaf-first: fewest same-graph importers first
    return (r["importers_js"], r["importers_total"], r["file"])


def cross_label(r):
    if not r["cross_domain_importers"]:
        return ""
    short = {"A_util": "A", "B_base": "B", "C_ui": "C", "D_views": "D",
             "E_complib": "E", "F_other": "F"}
    return ",".join(short.get(x, x) for x in r["cross_domain_importers"])


def render_table(rows):
    lines = [
        "| ☐ | Order | File | JS imp | TS imp | Leaf | Cross-stream importers |",
        "|---|-------|------|--------|--------|------|------------------------|",
    ]
    for i, r in enumerate(sorted(rows, key=order_key), 1):
        leaf = "yes" if r["is_leaf"] else ""
        lines.append(
            f"| [ ] | {i} | `{r['file']}` | {r['importers_js']} | {r['importers_ts']} "
            f"| {leaf} | {cross_label(r)} |"
        )
    return "\n".join(lines)


def main():
    ws_groups = collections.defaultdict(list)
    for r in ROWS:
        ws_groups[r["workstream"]].append(r)

    s = DATA["summary"]
    md = []
    md.append("# MetaMask Mobile JS → TS Migration — Step 0 Inventory\n")
    md.append(
        "Auto-generated by `scripts/js-ts-inventory.py` (data) and "
        "`scripts/js-ts-gen-doc.py` (this doc). Re-run both to refresh after "
        "conversions land.\n"
    )
    md.append("## Summary\n")
    md.append(f"- **Remaining `.js`/`.jsx` source files under `app/`: {s['js_source_files']}**")
    md.append(f"- Remaining `.js`/`.jsx` **test** files under `app/`: {s['js_test_files']}")
    md.append(f"- Total remaining JS files under `app/`: {s['total_js_files']}")
    md.append(f"- Import edges resolved (intra-`app/`): {s['import_edges_resolved']}\n")

    md.append("### Files per workstream\n")
    md.append("| Workstream | Source files |")
    md.append("|------------|--------------|")
    for w in ["A_util", "B_base", "C_ui", "D_views", "E_complib", "F_other"]:
        md.append(f"| {WS_TITLES[w]} | {len(ws_groups.get(w, []))} |")
    md.append("")

    md.append("### How to read the tables\n")
    md.append("- **Order**: suggested conversion order *within the stream* — leaf-first "
              "(fewest same-graph importers first). Types propagate to callers, so "
              "converting leaves first minimizes churn.")
    md.append("- **JS imp / TS imp**: number of other `app/` files (already-JS / already-TS) "
              "that import this file (in-degree).")
    md.append("- **Leaf**: `yes` = imported by no other `app/` file (safe to start anywhere).")
    md.append("- **Cross-stream importers**: which *other* workstreams import this file. "
              "Files with cross-stream importers should be converted **first, in their "
              "owning stream**, before dependent streams type against them.\n")

    md.append("### Shared / coordination files (append-only, expect minor merge conflicts)\n")
    md.append("- `app/declarations/index.d.ts` — add `declare module` entries for untyped deps.")
    md.append("- `package.json` — `@types/*` additions.\n")
    md.append("Every PR must pass `yarn lint:tsc`, `yarn lint`, `yarn test:unit`, and keep "
              "one file (or a tightly-coupled small folder) per PR "
              "(`chore(js-ts): Convert <path>.js to TypeScript`).\n")

    # Global hot-list: files imported across streams (highest risk of contention)
    hot = sorted([r for r in ROWS if r["cross_domain_importers"]],
                 key=lambda r: -r["importers_total"])[:30]
    md.append("### Convert-first hot list (widely-imported, cross-stream)\n")
    md.append("These are imported by many files across multiple streams — converting them "
              "early unblocks the most dependents.\n")
    md.append("| File | Total imp | JS | TS | Owning stream | Also imported by |")
    md.append("|------|-----------|----|----|---------------|------------------|")
    for r in hot:
        md.append(f"| `{r['file']}` | {r['importers_total']} | {r['importers_js']} "
                  f"| {r['importers_ts']} | {r['workstream'][0]} | {cross_label(r)} |")
    md.append("")

    # Per-workstream sections with sub-streams
    for w in ["A_util", "B_base", "C_ui", "D_views", "F_other"]:
        rows = ws_groups.get(w, [])
        if not rows:
            continue
        md.append(f"## {WS_TITLES[w]}\n")
        md.append(f"Total: **{len(rows)}** source files.\n")
        subs = collections.defaultdict(list)
        for r in rows:
            subs[substream(r)].append(r)
        if len(subs) > 1:
            md.append("Sub-streams (each can be a separate parallel session):\n")
            for name in sorted(subs):
                md.append(f"- **{name}** — {len(subs[name])} files")
            md.append("")
            for name in sorted(subs):
                md.append(f"### {name} ({len(subs[name])} files)\n")
                md.append(render_table(subs[name]))
                md.append("")
        else:
            md.append(render_table(rows))
            md.append("")

    # Test files appendix
    md.append("## Appendix — remaining `.js`/`.jsx` test files\n")
    md.append("Rename alongside the source file they cover (`.test.js`→`.test.ts(x)`).\n")
    for f in DATA["test_files"]:
        md.append(f"- [ ] `{f}`")
    md.append("")

    with open(os.path.join(OUT_DIR, "INVENTORY.md"), "w") as fh:
        fh.write("\n".join(md))
    print("wrote", os.path.join(OUT_DIR, "INVENTORY.md"))

    # Emit one ordered plain-text file list per (sub-)stream for direct handoff
    streams_dir = os.path.join(OUT_DIR, "streams")
    os.makedirs(streams_dir, exist_ok=True)
    stream_rows = collections.defaultdict(list)
    for r in ROWS:
        stream_rows[substream(r)].append(r)
    index = []
    for name in sorted(stream_rows):
        rows = sorted(stream_rows[name], key=order_key)
        slug = name.split(" ")[0].replace("/", "-").lower()
        path = os.path.join(streams_dir, f"{slug}.txt")
        with open(path, "w") as fh:
            fh.write(f"# {name} — {len(rows)} files, convert in listed order (leaf-first)\n")
            for r in rows:
                fh.write(r["file"] + "\n")
        index.append((name, slug, len(rows)))
    with open(os.path.join(streams_dir, "README.md"), "w") as fh:
        fh.write("# Per-stream ordered file lists\n\n")
        fh.write("Each `.txt` is a disjoint file set for one parallel Devin session, "
                 "ordered leaf-first. See `../INVENTORY.md` for full metadata.\n\n")
        for name, slug, n in index:
            fh.write(f"- `{slug}.txt` — {name} ({n} files)\n")
    print("wrote", len(index), "stream lists to", streams_dir)


if __name__ == "__main__":
    main()
