export let TOOLTIP_TYPES = /*#__PURE__*/function (TOOLTIP_TYPES) {TOOLTIP_TYPES["NETWORK_FEE"] = "network_fee";TOOLTIP_TYPES["REWARD_FREQUENCY"] = "reward_frequency";return TOOLTIP_TYPES;}({});




// These are the main Info components that are used in Confirmations
export let CONFIRMATION_EVENT_LOCATIONS = /*#__PURE__*/function (CONFIRMATION_EVENT_LOCATIONS) {CONFIRMATION_EVENT_LOCATIONS["PERSONAL_SIGN"] = "personal_sign";CONFIRMATION_EVENT_LOCATIONS["TYPED_SIGN_V1"] = "typed_sign_v1";CONFIRMATION_EVENT_LOCATIONS["TYPED_SIGN_V3_V4"] = "typed_sign_v3_v4";CONFIRMATION_EVENT_LOCATIONS["STAKING_DEPOSIT"] = "staking_deposit";CONFIRMATION_EVENT_LOCATIONS["STAKING_WITHDRAWAL"] = "staking_withdrawal";CONFIRMATION_EVENT_LOCATIONS["STAKING_CLAIM"] = "staking_claim";CONFIRMATION_EVENT_LOCATIONS["TRANSFER"] = "transfer";return CONFIRMATION_EVENT_LOCATIONS;}({});